version: "3.9"

services:
  db:
    image: postgres
    container_name: 2foryou_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=2foryou
      - POSTGRES_PASSWORD=admin
  web:
    build: .
    container_name: 2foryou_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=2foryou
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db